### ISSUE TITLE
Date picker needs to be validated twice + value incorrect

### ISSUE THREAD

**Issue by MathieuEnyosolutions** [enyosolutions-team/vue-awesome-components#124]
On Chrome:

In this first clip my first submission didn't work.
The second work :

https://user-images.githubusercontent.com/53440723/103860065-0d73e800-50b3-11eb-805f-ae2a8059ea83.mov

In this second clip the picker closed when I clicked on the hour (click on minutes worked well).
The second submission worked well :

https://user-images.githubusercontent.com/53440723/103860534-b28ec080-50b3-11eb-9c88-13dd61a60cc2.mov

The Javascript console of my browser says this on submission:
![image](https://user-images.githubusercontent.com/53440723/103859864-b2da8c00-50b2-11eb-85b2-0d524484bfd5.png)

The Vue DevTool says :
```
model:Object
expectedEndDate:"Invalid Date"
expectedStartDate:"Invalid Date"
isTemplate:true
title:"bla bla bla"
userId:13
```

**Comment by enyosolutions** [comment]
Which version of the component are you using?
Where did you have that bug (local or staging env)?

**Comment by MathieuEnyosolutions** [comment]
I was using the 1.2.6-beta-1
The package didn't update, it's my bad for not checking.

Here's a clip of the feature working well in the last version.
https://user-images.githubusercontent.com/53440723/103870430-9a26a200-50c3-11eb-8d81-ebe32cb8d91d.mov
